#ifndef __MESSAGETYPE_H__
#define __MESSAGETYPE_H__


typedef enum {
    // RECEIVED MESSAGE TYPES
    ARM_COMMAND,
    MANUAL_CONTROL,
    TAKE_OFF,
    // TO SEND MESSAGE TYPES
    ANSWER,
    DRONE_DATA,
    // GLOBAL
    UNKNOWN
} MESSAGE_TYPE;
#endif // __MESSAGETYPE_H__